table Measure
	lineageTag: 70a4b9a3-71bc-4fe7-aedd-88ead1ae575b

	measure AvgOvertimeperWk = IF(SUM(Employee_OverTime_Report[Jira_OverTime_Billable])>0,DIVIDE(SUM(Employee_OverTime_Report[Jira_OverTime_Billable]),MAX(Employee_OverTime_Report[weekNumber])))
		lineageTag: 6d91506e-9747-42c9-82fe-2e0bb408368e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Measure = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WSkxUio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

